// Mocks generated by Mockito 5.4.6 from annotations
// in apu_the_manager/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:apu_the_manager/data/datasources/file_search_remote_data_source.dart'
    as _i4;
import 'package:apu_the_manager/data/models/document_model.dart' as _i3;
import 'package:apu_the_manager/data/models/store_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStoreModel_0 extends _i1.SmartFake implements _i2.StoreModel {
  _FakeStoreModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentModel_1 extends _i1.SmartFake implements _i3.DocumentModel {
  _FakeDocumentModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FileSearchRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileSearchRemoteDataSource extends _i1.Mock
    implements _i4.FileSearchRemoteDataSource {
  MockFileSearchRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.StoreModel>> listStores() =>
      (super.noSuchMethod(
            Invocation.method(#listStores, []),
            returnValue: _i5.Future<List<_i2.StoreModel>>.value(
              <_i2.StoreModel>[],
            ),
          )
          as _i5.Future<List<_i2.StoreModel>>);

  @override
  _i5.Future<_i2.StoreModel> createStore(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#createStore, [displayName]),
            returnValue: _i5.Future<_i2.StoreModel>.value(
              _FakeStoreModel_0(
                this,
                Invocation.method(#createStore, [displayName]),
              ),
            ),
          )
          as _i5.Future<_i2.StoreModel>);

  @override
  _i5.Future<void> deleteStore(String? storeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStore, [storeId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.DocumentModel>> listDocuments(String? storeId) =>
      (super.noSuchMethod(
            Invocation.method(#listDocuments, [storeId]),
            returnValue: _i5.Future<List<_i3.DocumentModel>>.value(
              <_i3.DocumentModel>[],
            ),
          )
          as _i5.Future<List<_i3.DocumentModel>>);

  @override
  _i5.Future<_i3.DocumentModel> uploadDocument(
    String? storeId,
    _i6.File? file, {
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadDocument,
              [storeId, file],
              {#displayName: displayName},
            ),
            returnValue: _i5.Future<_i3.DocumentModel>.value(
              _FakeDocumentModel_1(
                this,
                Invocation.method(
                  #uploadDocument,
                  [storeId, file],
                  {#displayName: displayName},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.DocumentModel>);

  @override
  _i5.Future<void> deleteDocument(String? storeId, String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [storeId, documentId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
